(function(g){var window=this;var YY=function(a){a.g||(a.g=new g.Io,g.H(a,a.g));return a.g},ZY=function(a){a.N("cardstatechange",a.ud()&&a.ue()?1:0)},$Y=function(a){var b=g.Hh(a);
a=g.Oh(a);return new g.jh(b.x,b.y,a.width,a.height)},aZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},bZ=function(a){return"none"!=a.style.display},hna=function(a){var b=g.Bh(a,"fontSize");
var c=(c=b.match(ena))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Md){if(String(c)in fna)return g.Qh(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in gna)return a=a.parentNode,c=g.Bh(a,"fontSize"),g.Qh(a,b==c?"1em":b,"left","pixelLeft")}c=g.Rd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Xd(c);return b},ina=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Jk&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.vc("pollChoiceIndex"))},eZ=function(a){a=g.Pa(a);
delete cZ[a];g.Xb(cZ)&&dZ&&dZ.stop()},fZ=function(){dZ||(dZ=new g.M(function(){jna()},20));
var a=dZ;a.isActive()||a.start()},jna=function(){var a=(0,g.C)();
g.Kb(cZ,function(b){gZ(b,a)});
g.Xb(cZ)||fZ()},hZ=function(a,b){g.sf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},iZ=function(a,b,c,d){g.ho.call(this);
if(!g.Ja(a)||!g.Ja(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.B=d;this.coords=[];this.progress=this.D=0;this.A=null},gZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;jZ(a,a.progress);1==a.progress?(a.g=0,eZ(a),a.Xc(),a.l()):1==a.g&&a.yr()},jZ=function(a,b){g.Ma(a.B)&&(b=a.B(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},kZ=function(a,b,c,d,e){iZ.call(this,b,c,d,e);
this.element=a},lZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
kZ.call(this,a,b,c,d,e)},kna=function(a){return Math.pow(a,3)},lna=function(a){return 3*a*a-2*a*a*a},mZ=function(a){g.G.call(this);
this.i=a||window;this.g=[]},mna=function(a,b,c,d){c=(0,g.z)(c,d||a.i);
b=g.Mr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},nZ=function(a,b){(0,g.B)(b,function(c){g.Cs("visualElementShown",{csn:a,
ve:g.Ls(c),eventType:4},g.Hs,void 0,void 0)})},oZ=function(a,b){(0,g.B)(b,function(c){g.Cs("visualElementHidden",{csn:a,
ve:g.Ls(c),eventType:8},g.Hs,void 0,void 0)})},pZ=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Yc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={CD:a.impression,click:a.click,close:a.close,aM:a.teaser_impression,zs:a.teaser_click};b=b.tracking_params||{};this.A=g.Ks(b.card);this.D=g.Ks(b.teaser);this.u=g.Ks(b.icon)},qZ=function(a,b){g.Qf.call(this);
this.Dj=a;this.Ep=b;this[g.uf]=!1},vZ=function(a,b,c,d){qZ.call(this,a,b);
a=this.Ep;b=this.ia();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.v(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/nna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Ep;a=this.ia();if(d instanceof rZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof sZ){b="lg-"+d.u+"-"+d.B+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=tZ(c,"linearGradient",{x1:d.u,y1:d.B,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Da(d.l)&&(f+=";stop-opacity:"+d.l);f=tZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Da(d.o)&&(f+=";stop-opacity:"+d.o);d=tZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=uZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},wZ=function(){},xZ=function(a,b){qZ.call(this,a,b)},yZ=function(){this.Ua=[];
this.Ba=[];this.Nd=[]},zZ=function(a,b,c,d){var e=a.xd[0]-b*Math.cos(g.sd(d))+b*Math.cos(g.sd(d+90)),f=a.xd[1]-c*Math.sin(g.sd(d))+c*Math.sin(g.sd(d+90));
a.Ua.push(3);a.Ba.push(1);a.Nd.push(b,c,d,90,e,f);a.Gk=!1;a.xd=[e,f]},pna=function(a,b){for(var c=a.Nd,d=0,e=0,f=a.Ua.length;e<f;e++){var k=a.Ua[e],l=ona[k]*a.Ba[e];
b(k,c.slice(d,d+l));d+=l}},AZ=function(a,b,c,d){vZ.call(this,a,b,c,d)},BZ=function(a,b){this.g=a;
this.i=b},CZ=function(a,b,c,d,e){g.so.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.J=d||null},nna=function(a){var b=a.tj();
return b?b.width/(a.l?new g.wd(a.l,a.J):a.tj()).width:0},sZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.B=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ba(k)?k:null;this.o=g.Ba(l)?l:null},rZ=function(a,b){this.F=a;
this.H=null==b?1:b},DZ=function(a,b){qZ.call(this,a,b)},EZ=function(a,b,c,d){vZ.call(this,a,b,c,d)},FZ=function(a,b,c,d,e){CZ.call(this,a,b,c,d,e);
this.g={};this.O=g.Od&&!g.Cc(526);this.P=new g.kn(this)},tZ=function(a,b,c){a=a.M.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},GZ=function(a,b,c,d){b=tZ(a,"path",{d:qna(b)});
c=new EZ(b,a,c,d);a.o.ia().appendChild(c.ia())},qna=function(a){var b=[];
pna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},uZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+rna++;c.setAttribute("id",d);a.g[b]=d;a.B.appendChild(c);return d},sna=function(){HZ||(HZ=new g.Cg(400),HZ.start());
return HZ},IZ=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.F)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.F)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Ks(a.trackingParams));var k=(0,g.F)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.Vu=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.F)(u.loggingUrls||[],c);p.fl=g.Sb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.F)(n.impressionUrls||[],c);p.AD=(0,g.F)(n.hovercardShowUrls||[],c);p.Yc={itct:n.trackingParams};p.visualElement=g.Ks(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.dm=!1,p.On=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.dm=!1,p.On=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Sb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.dm=!1;p.On="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var y=d(r.subscribedButtonText);if(r.subscribed){var D=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else D=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var K=null;if(n.signinEndpoint&&(K=g.Sb(n,"signinEndpoint","webNavigationEndpointData","url"),!K)){n=void 0;break a}if(u&&(y||K)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:D,unsubscribeText:y,unsubscribeCount:E,enabled:r.enabled,signinUrl:K,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Sb(u,"urlEndpoint","url"),p.dm=!0,p.On="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Yd)(k,function(l){return!!l});
return f},JZ=function(a){g.ZJ.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.B={};this.A=this.l=null;this.J=[];a=g.V(a);this.P=g.Cy(a)||g.Dy(a);this.gA=!0;this.D=0;this.F=new g.Xn;this.u=new g.Qr(this);g.H(this,this.u);this.u.K(this.player,g.uD("creatorendscreen"),this.wE);this.u.K(this.player,"crx_creatorendscreen",this.xE);this.u.K(this.player,"resize",this.ob);this.u.K(window,"focus",this.jL);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},KZ=function(a){return a.player.getVideoData().Xb?"current":a.P?"new":"current"},LZ=function(a){return"creator-endscreen-editor"===a},MZ=function(a,b){g.HJ(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.B={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.D=0;if((a.i=b)&&b.elements){tna(a);c=[];var d=new g.rD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.V(a.player).g||(a.l=new g.T({C:"div",G:"ytp-ce-shadow"}),g.LJ(a.player,a.l.element,4),a.A=new g.vP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=una(a,e);a.g[e.id]=f;a.B[e.id]=e;g.LJ(a.player,f.element,4);var k=new g.rD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);vna(a,f,e)}g.EJ(a.player,
c);a.ob()}},tna=function(a){var b=g.$s(),c=g.at();
c&&b&&a.i.visualElement&&g.Ms(c,b,[a.i.visualElement],void 0)},una=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={C:"div",W:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.fl||"","aria-hidden":"true"},I:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:NZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{C:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Yn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={C:"div",W:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.fl||"","aria-hidden":"true"},I:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:NZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{C:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Yn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-playlist-count",I:[{C:"div",
G:"ytp-ce-playlist-icon"},{C:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={C:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.fl||"","aria-hidden":"true"},I:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",I:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",
I:[{C:"div",G:"ytp-ce-expanding-overlay-body",I:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",I:[{C:"a",W:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.Yn(a.F,b.title||"")},U:b.title},b.subscribeButton?{C:"div",G:"ytp-ce-subscribe-container",I:[{C:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{C:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{C:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:NZ(b)}]};c=new g.T(c);var d=g.Ed(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.V(a.player).g){var e=null;var f=b.Yc.itct}else e="endscreen",f=null;e=new g.mV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":c={C:"div",W:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.fl||"","aria-hidden":"true"},I:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",I:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",I:[{C:"div",G:"ytp-ce-expanding-overlay-body",I:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",
I:[{C:"div",G:"ytp-ce-website-title",L:{dir:g.Yn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-website-metadata",U:b.metadata},{C:"a",W:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:NZ(b)},{C:"div",G:"ytp-ce-expanding-icon",L:OZ(b.iconUrl)}]},c=new g.T(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},NZ=function(a){if(a.Vu)var b=a.Vu.thumbnails;
return OZ(b?b[b.length-1].url:null)},OZ=function(a){return a?{style:"background-image: url("+a+")"}:{}},vna=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.da("mouseenter",(0,g.z)(a.Kq,a,b,c));b.da("mouseleave",(0,g.z)(a.Fr,a,b,c));g.V(a.player).g||b.da("click",(0,g.z)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.da("click",(0,g.z)(a.oy,a,c));b.da("keypress",(0,g.z)(a.oy,a,c));b.da("focus",(0,g.z)(function(l,m){this.Kq(l,m)},a,b,c));
b.da("blur",(0,g.z)(function(l,m){this.Fr(l,m)},a,b,c));
b.da("touchstart",(0,g.z)(a.Kq,a,b,c));var f=g.Gd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.eo(b.element,"ytp-ce-element-hover");g.eo(b.element,"ytp-ce-force-expand")});
b.da("keydown",(0,g.z)(function(l,m){this.gA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.z)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),PZ(this,m.id,!0)):(g.eo(l.element,"ytp-ce-force-expand"),g.eo(l.element,"ytp-ce-element-hover"),PZ(this,m.id,!1))},a,b,c);
a=(0,g.z)(function(l,m){m&&(l.da("blur",function(){bZ(m)&&this.gA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Gd("ytp-sb-subscribe",b.element));a(g.Gd("ytp-sb-unsubscribe",b.element));b.da("focus",d);b.da("blur",e)},PZ=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.L(a.g[d].element,"ytp-ce-element-shadow-show",c)},QZ=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||LZ(g.V(a.player).playerStyle))c&&c();else{b=wna(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Zq(b[a],d)}},RZ=function(a,b,c){QZ(a,b.clickUrls,c);
(a=g.at())&&b.dm&&g.Os(a,b.visualElement)},wna=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(xna(b[e],c));return d},xna=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},SZ=function(a){return g.Ja(a)&&a.length?a[0]:a},TZ=function(a){var b=/.+/;
return g.v(a)&&null!=b&&null!=a&&a.match(b)?a:""},UZ=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},VZ=function(a){return g.v(a)?a:""},WZ=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},XZ=function(a,b){return"true"==a||"false"==a?"true"==a:b},YZ=function(a,b){return g.v(a)?parseFloat(a):b},ZZ=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.od(a,b,c);if(a>=b&&a<=c)return a}return e},yna=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.B)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},$Z=function(a,b){if(null==a)return null;
if(g.Ka(a)){var c=[];(0,g.B)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},zna=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.gh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},Ana=function(a){function b(c){return(0,g.Yd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},Bna=function(a){this.externalId=a},Cna=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},a_=function(a){if(!a)return null;
var b=g.Wc(VZ(a.value));b=g.Tc(b);if(!b)return null;var c=WZ(a.target,Dna,"current");return null==c?null:new Cna(b,c,XZ(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},b_=function(a){return a.value?a.value:null},Ena=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Hna=function(a){if(!a)return null;
var b=WZ(a.type,Fna),c=WZ(a.trigger,Gna),d=SZ(a.url);d=a_(d?d:null);a=SZ(a.subscribeData);var e=a?a:null;e?(a=VZ(e.external_user_id),e=VZ(e.subscription_token),a=a&&e?new Bna(a):null):a=null;return b?new Ena(b,c,d,a):null},c_=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},d_=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},e_=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Ji=c;this.l=d;this.t=e;this.u=f;this.A=k;this.B=l;this.o=m;this.i=n;this.g=p},f_=function(a,b){if(!a)return null;
var c=YZ(a.x,0),d=YZ(a.y,0),e=YZ(a.w,0),f=YZ(a.h,0),k=yna(a.t),l=YZ(a.d,0),m=YZ(a.px,0),n=YZ(a.py,0),p=YZ(a.scaleSlope,1),r=YZ(a.scaleSlopeX,p);p=YZ(a.scaleSlopeY,p);var u=WZ(a.scaleDimension,Ina,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},i_=function(a,b){var c=g_(b,h_(a,new g.jh(a.x,a.y,a.Ji,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.od(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.od(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},h_=function(a,b,c){var d=a.A,e=a.B,f=a.g?a.g:"xy",k=c_(c,a.o,f);
a=d_(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.jh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},j_=function(a){return a?f_(a,function(b,c,d,e,f,k,l,m,n,p,r){return new e_(b,c,d,e,f,k,l,m,n,p,r)}):null},k_=function(a,b){this.g=a;
this.i=b||null},g_=function(a,b){var c=a.i?i_(a.i,new k_(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.td?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Da(c)&&(d.top+=c));return d},l_=function(a,b,c,d,e,f,k,l,m,n,p,r,u){e_.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},Jna=function(a){if(!a)return null;
var b=YZ(a.sx,0),c=YZ(a.sy,0);return f_(a,function(d,e,f,k,l,m,n,p,r,u,y){return new l_(d,e,f,k,l,b,c,m,n,p,r,u,y)})},Kna=function(a,b,c,d,e,f,k,l,m,n,p,r,u,y){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=y},m_=function(a){if(!a)return null;
var b=UZ(a.fgColor,"#1A1A1A"),c=UZ(a.bgColor,"#FFF"),d=UZ(a.borderColor,"#000"),e=ZZ(a.borderWidth,0,5,!1,0),f=ZZ(a.bgAlpha,0,1,!1,.8),k=UZ(a.highlightFontColor,"#F2F2F2"),l=ZZ(a.highlightWidth,0,5,!1,3),m=VZ(a.textAlign),n=ZZ(a.textSize,3.3,30.1,!0,3.6107),p=VZ(a.fontWeight),r=zna(a.padding),u=Ana(a.effects),y=ZZ(a.cornerRadius,0,10,!0,0);a=SZ(a.gradient);if(a=a?a:null){var D=ZZ(a.x1,0,100,!0,0),E=ZZ(a.y1,0,100,!0,0),K=ZZ(a.x2,0,100,!0,100),Y=ZZ(a.y2,0,100,!0,100),la=UZ(a.color1,"#FFF"),Ra=UZ(a.color2,
"#000");a=new Lna(D,E,K,Y,la,Ra,ZZ(a.opacity1,0,100,!0,100),ZZ(a.opacity2,0,100,!0,0))}else a=null;return new Kna(b,c,d,e,f,k,l,m,n,p,r,u,y,a)},Lna=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.B=k;this.D=l},Mna=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},Ona=function(a){if(!a)return null;
var b=WZ(a.type,Nna,"rect"),c=$Z(a.rectRegion,j_),d=$Z(a.anchoredRegion,Jna);a=$Z(a.shapelessRegion,j_);return new Mna(b,c,d,a)},n_=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},Pna=function(a,b){this.i=a;
this.g=b},Qna=function(a,b){this.state=a;
this.ref=b},o_=function(a){if(!a)return null;
var b=WZ(a.state,Rna);a=TZ(a.ref);return b?new Qna(b,a):null},Sna=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},Tna=function(a){if(!a)return null;
var b=$Z(a.condition,o_),c=$Z(a.notCondition,o_),d=XZ(a.show_delay,!1);a=XZ(a.hide_delay,!1);return b||c?new Sna(b,c,d,a):null},Una=function(a,b,c){(0,g.B)(a.g,g.Qa(b,!1),c);
(0,g.B)(a.l,g.Qa(b,!0),c)},p_=function(a,b,c,d,e,f,k,l,m,n,p,r,u,y){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.B=l||[];this.i=m;this.A=n;this.u=p;this.data=r;this.g=u;this.itct=y},Xna=function(a){if(!a)return null;
var b=TZ(a.id),c=TZ(a.author),d=WZ(a.type,Vna),e=WZ(a.style,q_),f=VZ(SZ(a.TEXT)),k=VZ(a.data);k=0!=k.length?JSON.parse(k):{};var l=SZ(a.segment);var m=l?l:null;m?(TZ(m.timeRelative),l=TZ(m.spaceRelative),l=(m=$Z(m.movingRegion,Ona))?new Pna(l,m):null):l=null;m=$Z(a.action,Hna);var n=$Z(a.trigger,Tna),p=SZ(a.appearance);(p=m_(p?p:null))||(p=m_({}));var r=WZ(a.coordinate_system,Wna,"video_relative"),u=XZ(a.closeable,!0),y=VZ(a.log_data);a=VZ(a.itct);return b&&d?new p_(b,c,d,e,f,l,m,n,p,r,u,k,y,a):null},
s_=function(a){return r_(a,function(b){return"click"==b.trigger})},r_=function(a,b){return(0,g.Rj)(a.l,b,void 0)},Yna=function(a,b,c){(0,g.B)(a.l,b,c)},Zna=function(a,b){return g.Xa(a.l,b,void 0)},t_=function(a,b,c){(0,g.B)(a.B,b,c)},$na=function(a,b){(0,g.F)(a.B,b,void 0)},v_=function(a){return(a=u_(a))?n_(a):null},u_=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},w_=function(a,b){var c=v_(a);
return c&&b?d_(b,c.i,c.g?c.g:"xy"):1},y_=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;Una(b,function(d,e){var f=x_(e.state,e.ref);this.i.subscribe(f,(0,g.z)(this.o,this,f,d));this.g[f]=d},this)},x_=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},z_=function(){this.g=!1;
this.u=this.i=null},A_=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new FZ(b,c,void 0,void 0,void 0),a.i=b,a.i.Jp(),a.u=g.Rd("DIV"),a.u.appendChild(a.i.ia()));
return a.i},B_=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Kb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},C_=function(a,b){var c=g.ro(g.qo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},aoa=function(a,b){var c=C_(a,B_("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=C_(a,B_("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},B_("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=C_(a,B_("feComposite",{"in":c,in2:b,operator:"in"}));return C_(a,B_("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},boa=function(a,b){var c=C_(a,B_("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=C_(a,B_("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=C_(a,B_("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=C_(a,B_("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=C_(a,B_("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=C_(a,B_("feComposite",{operator:"out","in":c,in2:d}));return C_(a,B_("feComposite",{operator:"over","in":b,in2:c}))},coa=function(a,b){return b},doa=function(a){var b=
B_("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.B)(a,function(d){a:{switch(d){case "bevel":d=aoa;break a;case "dropshadow":d=boa;break a}d=coa}c=d(b,c)});
return b},eoa=function(a){a=(0,g.Yd)(a,function(b){return b in D_});
g.qb(a,function(b,c){return D_[b]-D_[c]});
return a},foa=function(a){return g.Xa(a,function(b){return"dropshadow"==b})?new g.gh(0,7,7,0):new g.gh(0,0,0,0)},E_=function(a,b,c){var d=new yZ;
d.moveTo(a.left+b+c,a.top+c);d.Wb(a.left+a.width-b-c,a.top+c);zZ(d,b,b,-90);d.Wb(a.left+a.width-c,a.top+a.height-b-c);zZ(d,b,b,0);d.Wb(a.left+b+c,a.top+a.height-c);zZ(d,b,b,90);d.Wb(a.left+c,a.top+b+c);zZ(d,b,b,180);d.close();return d},F_=function(a,b,c,d){var e=a.u;
e?a=new sZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.B,e.D):(b=a.g,a=new rZ(a.bgColor,d?Math.max(b,.9):b));return a},G_=function(a,b){var c=g.kh(a),d=foa(b);
g.Na(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.jh(c.left,c.top,c.right-c.left,c.bottom-c.top)},H_=function(a,b,c){if(c.length&&(b=g.Ed(document,"g",void 0,b),b.length)){var d=eoa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=doa(d),a=0<d.childNodes.length?uZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},I_=function(){z_.call(this);
this.o=0},goa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},J_=function(a){z_.apply(this,arguments)},K_=function(a){z_.apply(this,arguments)},L_=function(a){I_.apply(this,arguments)},M_=function(a,b,c,d,e){g.G.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Y=e;this.F=!1;this.ca=new mZ(this);g.H(this,this.ca);this.M=this.u=this.B=this.P=this.i=null;this.V=!1;this.ba=this.H=this.J=null;this.Tm=new g.Dl(this.cD,100,this);g.H(this,this.Tm);this.D=new g.M(this.ew,500,this);g.H(this,this.D);this.O=this.l=this.o=null},hoa=function(a,b){var c=(0,g.z)(function(d,e,f){e=f?N_(this,e,(0,g.z)(f,this)):N_(this,e);
this.ca.da(b,d,e)},a);
c("mouseover","G",a.ax);c("mouseout","F",a.pg);c("click","D");c("touchend","D")},ioa=function(a){if(a.g.u){if(r_(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Rd("DIV","annotation-close-button"),g.Ph(a.o,!1),g.Mp(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.ca.da(b,"click",N_(a,"E",c));a.ca.da(b,"touchend",N_(a,"E",c))}},N_=function(a,b,c){return(0,g.z)(function(d){if(this.Y)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Ph(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.he(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Ph(e,
!0)}}e=$Y(d.target);d=new g.td(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.N(b,this.g)},a)},Q_=function(a){if(a.i||a.l){var b=v_(a.g);
if(b){var c=O_(a);if(a.i){b=i_(b,c);var d=g.vJ(a.A).getVideoContentRect();g.Nh(a.i,b.width,b.height);g.Dh(a.i,b.left,b.top);a.P=new g.jh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=v_(a.g))&&d?c_(d,e.o,e.g?e.g:"xy"):1;var f=w_(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.gh(d,d,d,d));d=new g.gh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.B&&(a.B.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.vJ(a.A).getVideoContentRect();var p=g.CJ(a.A);g.lh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=P_(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Nh(a.u,f.width,f.height);g.Dh(a.u,f.left,f.top)}a.o&&(r?b=new g.td(r.left+
r.width-23-18,a.V?r.top+2:r.top+r.height-18-2):(r=P_(a,18,b,d,e),b=new g.td(r.left,r.top),g.Nh(a.o,r.width,r.height)),g.Dh(a.o,b));a.M=new g.jh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.J=a.ca.da(g.vJ(a.A),"mousemove",a.kF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.wd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.jh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.jh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Nh(a.u,
r.width,r.height),g.Dh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Dh(a.o,r&&e?new g.td(b.width-9,-9):r?new g.td(b.width-9,45<b.height?9:b.height-9):e?new g.td(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.td(45<b.width?b.width-9-18:-9,b.height-9):new g.td(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.vJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
w_(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Gd("annotation-link-icon",a))?bZ(b):!1;e=(d=g.Gd("annotation-close-button",a))?bZ(d):!1;r&&g.Ph(b,!1);e&&g.Ph(d,!1);m=f="";if(n=g.Gd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=hna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Ph(d,!0);r&&g.Ph(b,!0)}}}},P_=function(a,b,c,d,e){var f=0<e;
b=new g.jh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.V=!0);return b},R_=function(a){return"label"!=a.g.style||a.l.g},O_=function(a){var b=g.vJ(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.vJ(a.A).getPlayerSize();b=new g.jh(-b.left,-b.top,c.width,c.height)}else b=new g.jh(0,0,b.width,b.height);return new k_(b,a.O?v_(a.O):null)},S_=function(a,b){return b?new g.jh(a.x+b.left,a.y+b.top,b.width,b.height):null},T_=function(a,b,c){g.G.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;joa(b,a)},joa=function(a,b){$na(a,function(c){return new y_(a.id,c,b)})},U_=function(a){a.i.unsubscribe("resize",a.Zw,a);
a.i.unsubscribe("onVideoAreaChange",a.Qy,a)},V_=function(a){a.g&&(a.g.stop(),a.g=null)},W_=function(a,b,c){pZ.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=a_({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},X_=function(a,b,c){pZ.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=a_({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=a_({target:"current",value:a});this.J=b.signin_title||null;this.H=b.signin_message||null},Y_=function(a,b,c){X_.call(this,a,b,c);
this.F=b.ypc_flow_type;this.B=b.innertube_request_params},Z_=function(a,b,c){pZ.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=a_({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},$_=function(a,b,c){pZ.call(this,a,b,c);
this.B=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=a_({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},a0=function(a,b,c){X_.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new koa(a[b]))},koa=function(a){this.merchant=g.qc(a.merchant);
this.price=g.qc(a.price)},b0=function(a,b,c){X_.call(this,a,b,c);
this.P=b.ypc_item_type;this.F=b.ypc_item_id;this.B=b.ypc_flow_type},c0=function(a,b,c){pZ.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=a_({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},d0=function(a,b,c){pZ.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.B=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=a_({target:b.target||"new",value:b.url})},loa=function(a){this.g=a;
this.i={}},moa=function(a){var b={};
b=(b["iv-event"]=1,b);g.BJ(a.g,"iv",b,void 0)},h0=function(a,b,c,d){if(b){var e=e0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=f0(a,"cta_annotation_shown",e,c);g0(a,e,noa(b,d))}},i0=function(a,b,c,d,e,f){if(b){var k=e0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.ec(k,d);b=f0(a,"cta_annotation_clicked",k,e);g0(a,k,b,c,f)}},j0=function(a,b){if(b){var c=e0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=f0(a,"cta_annotation_closed",c);g0(a,c,d)}},noa=function(a,b){return b?(0,g.F)(a,g.Qa(function(c,d){return g.nn(d,c)},b)):a},f0=function(a,b,c,d){d=d?g.gb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.V(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.hu){if((b=a.hu[b])&&g.Xu(b)){a=g.lc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.kn){b=g.nq(a.kn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},g0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.B)(c||[],function(n){f++;
g.Zq(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.BJ(a.g,"iv",b,m)},e0=function(a,b){var c={};
if(b){var d=new g.bn(b);(0,g.B)(d.Fd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.V(a.g).playerStyle;return c},k0=function(a,b,c,d,e){e=e0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;g0(a,e,d)},l0=function(a,b,c,d){c&&(c=e0(a,c),c["iv-event"]=b,g0(a,c,d))},ooa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.rb=c;this.videoData=d;this.logger=e;this.Z=f;this.i=k},m0=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.Xn},poa=function(a,b){var c=[];
(0,g.B)(b.choices,function(k){c.push({C:"li",G:b.B+"-"+k.index.toString(),I:[{C:"label",I:[{C:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.B+k.index.toString(),value:k.index.toString(),"data-poll-choice-index":k.index.toString()}},{C:"span",G:"iv-card-poll-choice-text",I:[{C:"span",G:"iv-card-poll-choice-percent"},n0(this,"span",void 0,k.desc)]}]},{C:"div",G:"iv-card-poll-result",I:[{C:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={C:"ul",L:{role:"radiogroup"},I:c},e={};b.o&&(e["aria-label"]=g.KM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{C:"div",G:"iv-card-content",I:[n0(a,"h2",e,b.title),{C:"form",I:[{C:"fieldset",I:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({C:"div",W:["iv-card-sign-in"],I:[{C:"h2",U:"Want to vote?"},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:b_(b.o)},I:[{C:"span",W:["iv-button-content"],U:"Sign in"}]}]}));f=new g.T({C:"div",
W:f,I:d});d=f.element;o0(b,d);mna(a.g.g,d,g.Qa(a.B,b),a);(0,g.B)(g.Fd("iv-card-poll-choice-input",d),function(k){this.g.g.da(k,"focus",g.Qa(this.l,!0));this.g.g.da(k,"blur",g.Qa(this.l,!1))},a);
b.o&&(d=g.Gd("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Yc,b.l,b.i.click,5));return f},s0=function(a,b,c,d){var e=b.displayDomain?{C:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=p0(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{C:"a",G:"iv-click-target",L:{href:b_(b.url)},I:[q0(b.imageUrl,e),{C:"div",G:"iv-card-content",I:[n0(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({C:"div",W:["iv-card-sign-in"],I:[n0(a,"h2",void 0,b.J||""),{C:"p",U:b.H},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:b_(b.g)},I:[n0(a,"span","iv-button-content","Sign in")]}]});k=new g.T({C:"div",W:k,I:e});r0(a,k,b,c,d);return k},u0=function(a,
b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.B&&b.o?{C:"span",W:d,L:e,U:b.o}:"";c={C:"div",W:["iv-card",c],I:[{C:"a",G:"iv-click-target",L:{href:b_(b.url)},I:[q0(b.F,d?{C:"div",G:"iv-card-image-text",I:[d,b.priceText]}:""),{C:"div",G:"iv-card-content",I:[{C:"h2",G:"iv-card-primary-link",U:b.title},t0(a,b)]}]}]};c=new g.T(c);r0(a,c,b);return c},v0=function(a,b){return b.customMessage?n0(a,"div","iv-card-message",
b.customMessage):""},q0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{C:"div",G:"iv-card-image",L:{style:c},I:d}},t0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.B)(b.metaInfo,function(d){c.push(n0(this,"li","",d))},a);
return{C:"ul",G:"iv-card-meta-info",I:c}},n0=function(a,b,c,d){c?g.v(c)?c={"class":c}:g.Ja(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Yn(a.i,d);return{C:b,L:c,U:d}},p0=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.Yn(a.i,b.customMessage);var e=[{C:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({C:"span",G:"iv-card-link-icon"}));return{C:"div",W:c,L:d,I:e}},o0=function(a,b){var c=0;
(0,g.B)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Gd(a.B+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.Gd("iv-card-poll-choice-percent",f);g.ce(l,g.KM("$PERCENT%",{PERCENT:k}));f=g.Gd("iv-card-poll-result-bar",f);g.vh(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.g);g.L(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},w0=function(a,b,c,d){d?(c&&a.g.videoData.sa||a.g.Z.pauseVideo(),a.g.Z.isFullscreen()&&a.g.Z.toggleFullscreen(),i0(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.at())&&g.Os(a,b.A)):b.url&&a.u(b.url,b.id,b.Yc,b.l,b.i.click||[],5)},r0=function(a,b,c,d,e){c.g&&x0(a,g.Fd("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&x0(a,g.Fd("iv-click-target",b.element),c,c.url,d)},x0=function(a,b,c,d,e){(0,g.B)(b,function(f){if(e){var k=(0,g.z)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.da(f,"click",k)}else d&&this.o(f,d,c.id,c.Yc,c.l,c.i.click,5)},a)},y0=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},A0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=z0(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},z0=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},qoa=function(a){a=b_(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!A0(a))||(b=g.Og(g.Ng(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.lq(a);if(!b||!b.v)return null;if(b=b.t)return y0(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.jq(a[1]))&&a.t?y0(a.t):-1},B0=function(a){a=b_(a);
a=a.replace(/https?:\/\//g,"");return A0(a)?(a=g.lq(a))&&a.v?a.v:null:null},roa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},C0=function(a,b){return b?b:A0(a)?"current":"new"},D0=function(a,b){g.G.call(this);
this.Ca=a;this.context=b;this.Qs=!1;this.X=0},soa=function(a){return(0,g.C)()-a.X},toa=function(a,b,c,d,e,f){var k=b_(b);
if(k){var l=C0(k,b.target),m=(0,g.z)(function(){b.g&&this.context.Z.pauseVideo();var p=this.context.videoData.Xb||!1,r=g.lq(k||"");p&&r&&(r.v||r.list)?g.wX(this.context.Z.app,r.v,c,r.list,!1,void 0,void 0):g.RK(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=soa(a);i0(a.context.logger,d,m,n,e,f);A0(k)||(a=g.at(),d=c.itct,a&&d&&g.Os(a,g.Ks(d)))}},G0=function(a,b,c){D0.call(this,b,c);
var d=this;this.i=a;this.R=null;this.V=this.xa=this.u=this.ua=!1;this.ba=null;this.M=new g.M(g.Fa,c.rb.Mc?4E3:3E3);g.H(this,this.M);this.ka=new g.M(g.Fa);g.H(this,this.ka);this.A=new m0(c,(0,g.z)(this.yi,this),(0,g.z)(this.qm,this));this.F=new g.T({C:"div",G:"iv-drawer",L:{id:"iv-drawer"},I:[{C:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},I:[{C:"span",G:"iv-drawer-header-text"},{C:"button",W:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{C:"div",G:"iv-drawer-content"}]});
g.H(this,this.F);this.B=this.F.element;this.wa=new g.vP(this.F,330);g.H(this,this.wa);this.ya=g.Gd("iv-drawer-header-text",this.B);this.o=g.Gd("iv-drawer-content",this.B);this.l=[];this.na=this.O=this.D=this.Y=this.g=null;this.J=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&E0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.u)&&F0(d)});
this.P=this.H=this.aa=null},xoa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&H0[c]){c=new H0[c](b.id,b.data,b.g);if(!a.ua){g.co(a.ia(),["html5-stop-propagation","iv-drawer-manager"]);g.LJ(a.i,a.B,5);uoa(a);a.O=g.Gd("ytp-cards-button",a.i.getRootNode());var d=g.Gd("iv-drawer-close-button",a.B);a.na=d;a.ua=!0}I0(a,c.id);var e=voa(a,c);if(e){d={Gb:c,Po:e.element,Cw:!1};var f=woa(a,d);g.kb(a.l,f,0,d);e.g(a.o,f);a.ql();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Qa(a.OL,d)):(e=1E3*a.context.Z.getCurrentTime(),5E3>e&&e>c.startMs&&a.Mz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Qa(a.Mz,d)),J0(a))}}},yoa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){E0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){F0(a)});
var c=b.data.headerText;g.ce(a.ya,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.aa=g.Ks(b.data.trackingParams);a.P=g.Ks(b.data.closeTrackingParams);a.H=g.Ks(b.data.iconTrackingParams)},I0=function(a,b){var c=zoa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Gb.id),g.Xd(c.Po),g.cb(a.l,c),a.ql(),J0(a))},E0=function(a,b,c,d){if(!a.u){a.wa.show();
a.Y=new g.M(function(){g.J(a.context.Z.getRootNode(),"ytp-iv-drawer-open")},0);
a.Y.start();a.ba=g.Dr(a.o,"mousewheel",(0,g.z)(a.ME,a));a.u=!0;a.X=(0,g.C)();k0(a.context.logger,a.R,7,void 0,d&&d.Gb?d.Gb.l:void 0);var e=g.at();e&&a.aa&&a.P&&nZ(e,[a.aa,a.P]);var f={TRIGGER_TYPE:b};(0,g.B)(a.l,function(k){k.Cw||(k.Cw=!0,h0(a.context.logger,k.Gb.l,k.Gb.i.CD,f));e&&nZ(e,[k.Gb.A])});
ZY(a.i);c&&(a.D=new g.M(function(){a.ga=a.O;a.na.focus()},330),a.D.start())}},F0=function(a){a.u&&(a.wa.hide(),g.Er(a.ba),a.ba=null,g.eo(a.context.Z.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,ZY(a.i),a.D&&a.D.stop(),a.D=new g.M(function(){a.ga&&(a.ga.focus(),a.ga=null)},330),a.D.start())},uoa=function(a){var b=g.Gd("iv-drawer-close-button",a.B);
a.context.g.da(b,"click",a.fC,a);a.context.g.da(a.o,"touchend",function(){a.M.start()});
a.context.g.da(a.o,"scroll",a.pC,a);a.context.i.subscribe("onHideControls",function(){a.V=!0});
a.context.i.subscribe("onShowControls",function(){a.V=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.V=g.bo(a.i.getRootNode(),"ytp-autohide")});
a.J.push(g.Wp("iv-button-shown",a.UD,a));a.J.push(g.Wp("iv-button-hidden",a.TD,a));a.J.push(g.Wp("iv-teaser-shown",a.XD,a));a.J.push(g.Wp("iv-teaser-hidden",a.WD,a));a.J.push(g.Wp("iv-teaser-clicked",a.VD,a))},voa=function(a,b){switch(b.type){case "simple":return s0(a.A,b);
case "collaborator":var c=a.A,d={C:"div",W:["iv-card","iv-card-channel"],I:[{C:"a",W:["iv-click-target"],L:{href:b_(b.url),"data-ytid":b.channelId},I:[q0(b.profileImageUrl),{C:"div",G:"iv-card-content",I:[v0(c,b),{C:"h2",G:"iv-card-primary-link",U:b.title},t0(c,b)]}]}]};d=new g.T(d);r0(c,d,b);return d;case "donation":return c=a.A,d=(0,g.z)(c.A,c,b),s0(c,b,d,d);case "episode":return u0(a.A,b,"iv-card-episode");case "movie":return u0(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={C:"div",W:["iv-card",
"iv-card-playlist"],I:[{C:"a",G:"iv-click-target",L:{href:b_(b.url)},I:[q0(b.o,{C:"div",G:"iv-card-image-overlay",I:[{C:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{C:"div",G:"iv-card-content",I:[v0(c,b),n0(c,"h2","iv-card-primary-link",b.title),t0(c,b)]}]}]},d=new g.T(d),r0(c,d,b),d;case "poll":return poa(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=p0(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({C:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({C:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={C:"div",I:k});d={C:"div",W:d,L:{tabindex:"0"},I:[{C:"a",W:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:b_(b.url),"aria-hidden":"true",tabindex:"-1"}},{C:"div",G:"iv-card-content",I:[b.sponsored?{C:"div",G:"iv-card-sponsored",I:["Sponsored",{C:"div",G:"iv-ad-info-container",I:[{C:"div",G:"iv-ad-info",U:"{{adInfo}}"},
{C:"div",G:"iv-ad-info-icon-container",I:[{C:"div",G:"iv-ad-info-icon"},{C:"div",G:"iv-ad-info-callout"}]}]}]}:"",{C:"a",G:"iv-click-target",L:{href:b_(b.url)},I:[n0(c,"h2",f,b.title),k]}]}]};d=new g.T(d);f=g.Sd("span");g.ce(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.kb(f,"adInfo");r0(c,d,b);return d;case "tip":return c=a.A,d=(0,g.z)(c.D,c,b),s0(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{C:"span",W:["yt-badge",
"yt-badge-live"],U:"LIVE NOW"}:"",d={C:"div",W:["iv-card","iv-card-video"],I:[{C:"a",G:"iv-click-target",L:{href:b_(b.url)},I:[q0(b.o,b.videoDuration?{C:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{C:"div",G:"iv-card-content",I:[v0(c,b),n0(c,"h2","iv-card-primary-link",b.title),t0(c,b),d]}]}]},d=new g.T(d),r0(c,d,b),d}return null},woa=function(a,b){if(0==a.l.length)return 0;
var c=g.Ya(a.l,function(d){return b.Gb.startMs>d.Gb.startMs||b.Gb.startMs==d.Gb.startMs&&b.Gb.timestamp>=d.Gb.timestamp?!0:!1});
return-1==c?0:c+1},Aoa=function(a){return a.g?"productListing"==a.g.Gb.type:(0,g.Ri)(a.l,function(b){return"productListing"==b.Gb.type})},J0=function(a){g.L(a.i.getRootNode(),"ytp-cards-shopping-active",Aoa(a))},K0=function(a,b){if(a.F.Fa()){var c=new iZ([0,
a.o.scrollTop],[0,b.Po.offsetTop],600,lna);a.context.l.da(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.da(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.NB(a.F,!0),a.o.scrollTop=b.Po.offsetTop,g.NB(a.F,!1)},L0=function(a){return a.g&&a.g.Gb?a.g.Gb:a.l[0]&&a.l[0].Gb?a.l[0].Gb:null},zoa=function(a,b){return g.Xa(a.l,function(c){return c.Gb.id==b})},M0=function(a,b,c){D0.call(this,a,b);
this.annotation=c;this.isActive=!1},Boa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},N0=function(a,b,c){M0.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.B=this.A=null},O0=function(a,b,c){M0.call(this,a,b,c);
this.F=this.u=this.H=!1;this.B=5E3;this.o=null;this.D=g.Rd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Ph(this.l,!1);g.Ph(this.i,!0)},700,this);
g.H(this,this.A)},Coa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.B=b.collapse_delay_ms||a.B;var d=["iv-promo","iv-promo-inactive"];a.ia().setAttribute("aria-hidden",!0);a.ia().setAttribute("aria-label","Promotion");a.ia().tabIndex=0;var e=a.annotation.Hb(),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Rd("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.yi(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.ld(f,b_(e)),a.g=f):a.g=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.Q(a.context.rb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var p=g.Rd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.yi(a.ia(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.J(a.g,"iv-click-target");e&&a.yi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=
g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.g,"iv-click-target"),e&&a.yi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Rd("DIV","iv-promo-actions");a.i=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.g.da(a.i,
"click",g.Qa(a.Lp,5E3),a);c.appendChild(a.i);g.Ph(a.i,!1);a.context.g.da(a.ia(),"mouseover",a.eD,a);a.context.g.da(a.ia(),"mouseout",a.dD,a);a.context.g.da(a.ia(),"touchend",g.Qa(a.Lp,5E3),a);a.l=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.g.da(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.WC:a.VC,a);c.appendChild(a.l);g.co(a.ia(),d);k&&(a.ia().appendChild(k),n&&k.appendChild(n));a.ia().appendChild(a.D);a.ia().appendChild(c)},P0=function(a){a.u||a.F||a.o||(g.J(a.ia(),
"iv-promo-collapsed"),a.u=!0,a.A.start())},Q0=function(a){a.A.stop();
a.u&&(g.fo(a.ia(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Ph(a.i,!1),g.Ph(a.l,!0))},S0=function(a,b){a.o||(a.o=g.Dg(function(){R0(this);
P0(this)},b,a))},R0=function(a){a.o&&(g.w.clearTimeout(a.o),a.o=null)},T0=function(a){g.ZJ.call(this,a);
this.J=!1;this.H=0;this.i={};this.P={};this.D=new loa(a);this.A=new g.Qr(this);g.H(this,this.A);this.B=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.z)(this.N,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.z)(this.N,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.z)(this.N,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.z)(this.N,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.z)(this.N,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.uI,this);this.subscribe("onShowControls",this.wK,this);this.subscribe("presentingplayerstatechange",this.EJ,this);this.subscribe("resize",this.Gr,this);this.subscribe("G",this.uE,this);this.subscribe("F",this.pg,this);this.subscribe("D",this.tH,this);this.subscribe("E",this.WH,this);g.V(this.player).J.subscribe("vast_info_card_add",this.Py,this);this.R=new g.Qr(this);g.H(this,this.R);this.R.K(this.player,g.uD("annotations_module"),this.sE);this.R.K(this.player,
"crx_annotations_module",this.tE);this.O=g.Rd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.V=g.Rd("DIV","video-custom-annotations");this.u=new g.T({C:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.LJ(this.player,this.u.element,4);this.u.hide();this.o=new g.T({C:"div",W:["ytp-iv-video-content"]});g.H(this,this.o);g.Ud(this.o.element,g.Rd("DIV","video-annotations",this.O,this.V));this.F=this.g=null;this.M=[];Doa(this)&&this.load();var b=g.Sd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},U0=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Doa=function(a){var b=g.V(a.player);
a=a.player.getVideoData();return 1==(b.Mf||a.Mf)&&!a.LA||null!==b.J.get(a.videoId)},V0=function(a,b,c){a.J=!0;
a.B=g.Eq(b,c)},W0=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(W0(a,e))}return c},X0=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},Foa=function(a,b){var c=Eoa(a,b);
if(!c&&"marker"!=b.type)return null;t_(b,function(e){e=(0,g.z)(this.UK,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new T_(a.wa,b,c);g.H(d,c);return d},Goa=function(a,b){var c=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Ph(c,!1);var d=null;switch(b.type){case "branding":if(g.V(a.player).Kc)break;a.u.element.appendChild(c);d=new N0(c,Y0(a),b);break;case "promotion":g.LJ(a.player,c,4),d=new O0(c,Y0(a),b)}d&&d.In();return d},Hoa=function(a){var b=a.player.getVideoData();
if(b.Dd){var c=g.V(a.player),d=c.J.get(b.videoId);if(d){var e={format:"XML",Ac:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Ac.gaming="1");e.Xc=(0,g.z)(function(f,k,l){X0(this,f,k)||(f=g.yq(l)&&l.responseXML?l.responseXML:null)&&Z0(this,f)},a,a.H,b.videoId);
g.us()&&(e.Xc=$0(a,e.Xc));e.qb={ic_only:"1"};a1(e,d);a.J=!0;g.Eq(b.Dd,e)}}},a1=function(a,b){a.method="POST";
a.qb=a.qb||{};b.vl&&(a.qb.ic_coll=b.vl);b.wl&&(a.qb.ic_xml=b.wl);b.Es&&(a.qb.ic_track=b.Es)},Ioa=function(a){var b=new g.T({C:"div"});
g.Ph(b.element,!1);var c=new G0(a.player,b.element,Y0(a));g.H(c,b);b.g(a.u.element);c.In();return c},Y0=function(a){if(!a.F){var b=new mZ(a);
g.H(a,b);var c=new g.kn(a);g.H(a,c);a.F=new ooa(b,c,g.V(a.player),a.player.getVideoData(),a.D,a.player,a.wa)}return a.F},Z0=function(a,b){var c=!1;
Joa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=W0(a,d[e]),k=null;try{k=Xna(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=Goa(a,k))g.H(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=Ioa(a),g.H(a,a.g)),"card"==k.type?xoa(a.g,k):yoa(a.g,k),c=!0;else if(f=Foa(a,k))g.H(a,f),a.i[k.id]=f}}c&&(ZY(a.player),a.Gr());g.Kb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},Joa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.at();
if(b){var c=g.$s();c&&g.Ms(b,c,[g.Ks(a)])}}},Koa=function(a,b,c,d){d?b1(a,b,c):c1(a,b,c)},c1=function(a,b,c){if(b=a.i[b])V_(b),c&&c.i?(a=(0,g.z)(a.dw,a,b),b.g=new g.M(a,2E3),b.g.start()):a.dw(b)},b1=function(a,b,c){if(b=a.i[b])V_(b),c&&c.o?(a=(0,g.z)(a.Yz,a,b),b.g=new g.M(a,2E3),b.g.start()):a.Yz(b)},d1=function(a,b){var c=a.player.getVideoData();
if(!c.kl)return!1;var d=b_(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!A0(d))return!1;d=g.lq(d);return d.list||d.p?!1:(d=B0(b))?c.videoId==d?!0:"new"!=b.target&&g.V(a.player).i?!0:!1:!1},Eoa=function(a,b){if(Loa(b)){var c=b.u||r_(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new M_(b,(0,g.z)(a.O.appendChild,a.O),a.player,a.wa,c)}return null},Loa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in q_)if(a.style==q_[b])return!0;return!1},e1=function(a,b,c,d){a.N(x_(b,d),c,d)},$0=function(a,b){return(0,g.z)(function(){if(!this.ea()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Qa.apply(window,c);this.M.push(g.rs(b))}},a)};
g.pJ.prototype.wi=g.ca(14,function(a,b){var c=g.qJ(this).l;c&&c.wi(a,b)});
g.so.prototype.Jp=g.ca(0,function(){this.i=this.M.createElement("DIV")});
var ena=/[^\d]+$/,fna={cm:1,"in":1,mm:1,pc:1,pt:1},gna={em:1,ex:1},cZ={},dZ=null;g.A(hZ,g.sf);g.A(iZ,g.ho);g.h=iZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;eZ(this);this.startTime=a=(0,g.C)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Qd("play");-1==this.g&&this.Qd("resume");this.g=1;var b=g.Pa(this);b in cZ||(cZ[b]=this);fZ();gZ(this,a);return!0};
g.h.stop=function(a){eZ(this);this.g=0;a&&(this.progress=1);jZ(this,this.progress);this.Qd("stop");this.l()};
g.h.pause=function(){1==this.g&&(eZ(this),this.g=-1,this.Qd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Qd("destroy");iZ.Ha.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.yr=function(){this.Qd("animate")};
g.h.Qd=function(a){this.dispatchEvent(new hZ(a,this))};
g.A(kZ,iZ);kZ.prototype.u=g.Fa;kZ.prototype.yr=function(){this.u();kZ.Ha.yr.call(this)};
kZ.prototype.l=function(){this.u();kZ.Ha.l.call(this)};
kZ.prototype.o=function(){this.u();kZ.Ha.o.call(this)};
g.A(lZ,kZ);lZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(mZ,g.G);mZ.prototype.da=function(a,b,c,d){c=(0,g.z)(c,d||this.i);a=g.Dr(a,b,c);this.g.push(a);return a};
mZ.prototype.rm=function(a,b,c,d){c=(0,g.z)(c,d||this.i);a=g.Nr(a,b,c);this.g.push(a);return a};
mZ.prototype.Oa=function(a){g.Er(a);g.cb(this.g,a)};
mZ.prototype.T=function(){g.Er(this.g);this.g.length=0;g.G.prototype.T.call(this)};g.A(qZ,g.Qf);g.h=qZ.prototype;g.h.Ep=null;g.h.Dj=null;g.h.ia=function(){return this.Dj};
g.h.addEventListener=function(a,b,c,d){g.Cf(this.Dj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Kf(this.Dj,a,b,c,d)};
g.h.T=function(){qZ.Ha.T.call(this);var a=this.Dj;if(a)if(g.vf(a))a.ge&&g.zf(a.ge);else if(a=g.Ff(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Lf(d[e])&&++b}};g.A(vZ,qZ);vZ.prototype.fill=null;g.A(xZ,qZ);yZ.prototype.ye=null;yZ.prototype.xd=null;yZ.prototype.Gk=!0;var ona=[2,2,6,6,0];g.h=yZ.prototype;g.h.clear=function(){this.Ua.length=0;this.Ba.length=0;this.Nd.length=0;delete this.ye;delete this.xd;delete this.Gk;return this};
g.h.moveTo=function(a,b){0==g.Va(this.Ua)?this.Nd.length-=2:(this.Ua.push(0),this.Ba.push(1));this.Nd.push(a,b);this.xd=this.ye=[a,b];return this};
g.h.Wb=function(a){var b=g.Va(this.Ua);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ua.push(1),this.Ba.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Nd.push(c,d)}this.Ba[this.Ba.length-1]+=b/2;this.xd=[c,d]};
g.h.close=function(){var a=g.Va(this.Ua);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ua.push(4),this.Ba.push(1),this.xd=this.ye);return this};
g.h.clone=function(){var a=new this.constructor;a.Ua=this.Ua.concat();a.Ba=this.Ba.concat();a.Nd=this.Nd.concat();a.ye=this.ye&&this.ye.concat();a.xd=this.xd&&this.xd.concat();a.Gk=this.Gk;return a};
g.h.transform=function(a){if(!this.Gk)throw Error("Non-simple path");a.transform(this.Nd,0,this.Nd,0,this.Nd.length/2);this.ye&&a.transform(this.ye,0,this.ye,0,1);this.xd&&this.ye!=this.xd&&a.transform(this.xd,0,this.xd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ua.length};g.A(AZ,vZ);g.A(CZ,g.so);CZ.prototype.o=null;CZ.prototype.tj=function(){return this.Og?g.Oh(this.ia()):g.Da(this.width)&&g.Da(this.height)?new g.wd(this.width,this.height):null};
CZ.prototype.resume=function(){};g.A(sZ,wZ);g.A(rZ,wZ);g.A(DZ,xZ);DZ.prototype.clear=function(){g.Vd(this.ia())};
DZ.prototype.setSize=function(a,b){var c=this.ia(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.A(EZ,AZ);var HZ;g.A(FZ,CZ);var rna=0;g.h=FZ.prototype;g.h.Jp=function(){var a=tZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=tZ(this,"g");this.B=tZ(this,"defs");this.o=new DZ(b,this);a.appendChild(this.B);a.appendChild(b);this.i=a;this.l&&(this.ia().setAttribute("preserveAspectRatio","none"),this.O?this.AA():this.ia().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.J:"")))};
g.h.AA=function(){if(this.Og){var a=this.tj();0==a.width?this.ia().style.visibility="hidden":(this.ia().style.visibility="",this.o.ia().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.J+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Nh(this.ia(),a,b)};
g.h.tj=function(){if(!g.xh)return this.Og?g.Oh(this.ia()):FZ.Ha.tj.call(this);var a=this.width,b=this.height,c=g.v(a)&&-1!=a.indexOf("%"),d=g.v(b)&&-1!=b.indexOf("%");if(!this.Og&&(c||d))return null;if(c){var e=this.ia().parentNode;var f=g.Oh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ia().parentNode,f=f||g.Oh(e),b=parseFloat(b)*f.height/100);return new g.wd(a,b)};
g.h.clear=function(){this.o.clear();g.Vd(this.B);this.g={}};
g.h.jj=function(){FZ.Ha.jj.call(this);this.O&&this.P.Oa(sna(),"tick",this.AA)};
g.h.T=function(){delete this.g;delete this.B;delete this.o;this.P.dispose();delete this.P;FZ.Ha.T.call(this)};g.t(JZ,g.ZJ);g.h=JZ.prototype;
g.h.load=function(){g.ZJ.prototype.load.call(this);if(!LZ(g.V(this.player).playerStyle)){var a=g.vB(this.player.getVideoData());if(a)a=IZ(a,KZ(this)),MZ(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Xc:(0,g.z)(this.lI,this,a),Ac:{v:a},withCredentials:!0};"gaming"==g.V(this.player).playerStyle&&(a.Ac.gaming="1");this.P&&(a.Ac.ptype="embedded");var c=this.player.getVideoData().av;c&&(a.qb={ad_tracking:c});if(b=g.uB(b))if(b=g.Wc(b),b=g.Tc(b))this.o=
g.Eq(b,a)}}};
g.h.unload=function(){MZ(this,null);this.o&&(this.o.abort(),this.o=null);g.ZJ.prototype.unload.call(this)};
g.h.Vb=function(a,b){if(!LZ(g.V(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=IZ(b,"new");MZ(this,c);return!0}return null};
g.h.getOptions=function(){return LZ(g.V(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.lI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=IZ(c,KZ(this)))}MZ(this,c)};
g.h.ob=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<f1.length;f++){var k=Math.abs(b.width-f1[f]);if(-1==e||d>=k)e=f,d=k}d=g1[e];this.l&&g.vh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.B[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Nh(e.element,Math.round(k.width*a.width),f);g.Dh(e.element,m,n);g.fo(e.element,Moa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.fo(e.element,g1);g.J(e.element,d);(e=g.Ed(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.vh(e,"height",f+"px")}}}}};
g.h.wE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.yJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(QZ(this,this.i.impressionUrls),(a=g.at())&&this.i.visualElement&&g.Ns(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.B[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");QZ(this,c.impressionUrls);
(b=g.at())&&g.Ns(b,c.visualElement);g.V(this.player).tb&&this.player.ma("endscreenelementshown",a)}};
g.h.xE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.eo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.eo(b,"ytp-ce-shown");g.V(this.player).tb&&this.player.ma("endscreenelementhidden",a)}};
g.h.jL=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.fo(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.oy=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.bo(c,"ytp-ce-element");){g.bo(c,"subscribe-label")&&RZ(this,a);if(g.bo(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.bo(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Fr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.On?(RZ(this,a),this.Gz(),this.player.pauseVideo(),c=g.Wc(a.targetUrl),c=g.Tc(c),g.RK(c,void 0,a.Yc)):(c=this.player.getVideoData().Xb,
c=(0,g.z)(this.UL,this,c,a.targetUrl,a.Yc),c=(0,g.z)(this.Gz,this,c),RZ(this,a,c))}}};
g.h.UL=function(a,b,c){var d=g.lq(b);a&&d&&(d.v||d.list)?g.wX(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.QK(b,c)};
g.h.Kq=function(a,b){g.bo(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.V(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),QZ(this,b.AD),PZ(this,b.id,!0))};
g.h.Fr=function(a,b){g.eo(a.element,"ytp-ce-element-hover");g.eo(a.element,"ytp-ce-force-expand");PZ(this,b.id,!1)};
g.h.Gz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var f1=[346,426,470,506,570,640,853,1280,1920],g1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Moa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Dna={tN:"current",AO:"new"};var Fna={CLOSE:"close",EO:"openUrl",IB:"subscribe"},Gna={oN:"click",CLOSE:"close",VN:"hidden",eP:"rollOut",BB:"rollOver",DB:"shown"};var Ina={IP:"xx",JP:"xy",KP:"yx",LP:"yy"};g.t(l_,e_);var Nna={YA:"anchored",aP:"rect",hP:"shapeless"};var Rna={CLOSED:"closed",NO:"playerControlShow",BB:"rollOver",DB:"shown"};p_.prototype.Hb=function(){var a=Zna(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
p_.prototype.showLinkIcon=function(){return r_(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var q_={YA:"anchored",bB:"branding",CHANNEL:"channel",sN:"cta",XN:"highlightText",lO:"label",PLAYLIST:"playlist",QO:"popup",lP:"speech",IB:"subscribe",uP:"title",VIDEO:"video",EP:"website"},Vna={bB:"branding",fN:"card",zN:"drawer",WN:"highlight",tO:"marker",VO:"promotion",TEXT:"text",GP:"widget"},Wna={CP:"video_relative",OO:"player_relative"};y_.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Ob(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.N(this.u,a,d))};z_.prototype.ia=function(){return this.u};
z_.prototype.l=function(){};var D_={bevel:1,dropshadow:2};g.t(I_,z_);
I_.prototype.l=function(a,b){var c=v_(a);if(c){var d=i_(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=u_(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.mh(g_(b,h_(e,new g.jh(e.D,e.F,e.Ji,e.l),b.g))),k=d.clone();c=new g.jh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=G_(k,c.effects);l=A_(this,k.width,k.height);m=F_(c,k.width,k.height,this.g);
d=new g.jh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.td(f.x-k.left,f.y-k.top);this.o=17*d_(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&s_(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new BZ(r,p?f.i:f.borderColor):null)?f.g/2:0;r=goa(d,n);var u=this.A(d,e,n,r),y=n.x;n=n.y;var D=d.width,E=d.height,K=d.left;d=d.top;var Y=new yZ;Y.moveTo(K+e+p,d+p);"t"==r&&(Y.Wb(u.start,d+p),Y.Wb(y,n),Y.Wb(u.end,d+p));Y.Wb(K+D-e-p,d+p);zZ(Y,e,e,-90);"r"==r&&(Y.Wb(K+D-p,u.start),Y.Wb(y,n),Y.Wb(K+
D-p,u.end));Y.Wb(K+D-p,d+E-e-p);zZ(Y,e,e,0);"b"==r&&(Y.Wb(u.end,d+E-p),Y.Wb(y,n),Y.Wb(u.start,d+E-p));Y.Wb(K+e+p,d+E-p);zZ(Y,e,e,90);"l"==r&&(Y.Wb(K+p,u.end),Y.Wb(y,n),Y.Wb(K+p,u.start));Y.Wb(K+p,d+e+p);zZ(Y,e,e,180);Y.close();GZ(l,Y,f,m);if(m=this.ia())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Dh(m,k.left,k.top),g.Nh(m,k.width,k.height),H_(l,m,c.effects)}}}};
I_.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.od(k-f/2,l+b,l+m-f-b);return new g.fj(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.fj(0,0)};g.t(J_,z_);J_.prototype.l=function(a,b){var c=v_(a);if(c){var d=i_(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=G_(d,e.effects);var f=A_(this,c.width,c.height),k=new BZ(!e.l&&this.g?1:e.l,e.bgColor),l=new rZ("#000",0);d=E_(new g.jh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);GZ(f,d,k,l);f=this.ia();g.J(f,"annotation-shape");e=e.g;aZ(f,this.g?Math.max(e,.9):e);g.Dh(f,c.left,c.top);g.Nh(f,c.width,c.height)}}};g.t(K_,z_);
K_.prototype.l=function(a,b){var c=v_(a);if(c){var d=i_(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=G_(d,c.effects),f=A_(this,e.width,e.height),k=new g.jh(0,0,d.width,d.height);d=F_(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&s_(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new BZ(p,n?m.i:m.borderColor):null;k=E_(k,l,m?m.g/2+1:0);GZ(f,k,m,d);if(k=this.ia())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Dh(k,e.left,e.top),g.Nh(k,e.width,e.height),H_(f,k,c.effects)}}};g.t(L_,I_);L_.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.fj(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.fj(0,0)};g.t(M_,g.G);g.h=M_.prototype;g.h.ax=function(){this.F||(this.o&&g.Ph(this.o,!0),this.u&&g.Ph(this.u,!0),this.l&&(this.l.g=!0,aZ(this.i,R_(this)?1:0),this.l.l(this.g,O_(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.ca.rm(g.vJ(this.A),"mouseleave",function(a){this.Tm.stop();this.pg(a)}))};
g.h.pg=function(){this.F&&(this.M?this.D.start():this.ew(),this.l&&(this.l.g=!1,aZ(this.i,R_(this)?1:0),this.l.l(this.g,O_(this))),this.F=!1,this.H&&(this.ca.Oa(this.H),this.H=null))};
g.h.ew=function(){this.o&&g.Ph(this.o,!1);this.u&&g.Ph(this.u,!1)};
g.h.kF=function(a){this.ba=a;this.Tm.Bj()};
g.h.cD=function(){var a=this.ba,b=new g.td(a.clientX,a.clientY),c=g.Hh(this.A.getRootNode()),d=S_(c,this.P);c=(this.u&&bZ(this.u)||this.o&&bZ(this.o))&&S_(c,this.M);d&&d.contains(b)||c&&c.contains(b)?this.ax(a):this.pg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=O_(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new J_:"popup"==this.g.style?d=new K_:"anchored"==this.g.style?d=new I_:"speech"==this.g.style&&(d=new L_);d&&(d.l(this.g,c),this.l=d,c=d.ia())&&(g.Ph(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Rd("DIV",c);g.Ph(this.i,!1);this.g.o&&(this.B=g.Rd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.B,"player-label-text"),this.B.style.backgroundColor=this.g.i.bgColor),g.ce(this.B,this.g.o),this.i.appendChild(this.B));g.Mp(this.i,"annotation_id",this.g.id);this.R(this.i);hoa(this,this.i);if(s_(this.g)&&this.g.showLinkIcon()){if(d=this.g.Hb())c=this.i,d=new g.Wm(b_(d)),c.title=d.g+d.i;this.u=g.Rd("SPAN","annotation-link-icon");g.Ph(this.u,
!1);this.i.appendChild(this.u)}ioa(this);s_(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=n_(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ia()&&(this.l.ia().style.zIndex=a)}g.Ph(this.i,!0);aZ(this.i,R_(this)?1:0);Q_(this);this.l&&this.l.ia()&&g.Ph(this.l.ia(),!0)};
g.h.hide=function(){this.i&&g.Ph(this.i,!1);this.l&&this.l.ia()&&g.Ph(this.l.ia(),!1);this.J&&(this.ca.Oa(this.J),this.J=null)};g.t(T_,g.G);g.h=T_.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(U_(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.Zw,this),this.i.subscribe("onVideoAreaChange",this.Qy,this))};
g.h.destroy=function(){if(this.view){U_(this);var a=this.view,b=a.ca;g.Er(b.g);b.g.length=0;a.Tm.dispose();a.D.dispose();a.i&&g.Xd(a.i);a.l&&a.l.ia()&&g.Xd(a.l.ia())}V_(this)};
g.h.Qy=function(){Q_(this.view)};
g.h.Zw=function(){Q_(this.view)};g.t(W_,pZ);g.t(X_,pZ);g.t(Y_,X_);g.t(Z_,pZ);g.t($_,pZ);g.t(a0,X_);g.t(b0,X_);g.t(c0,pZ);g.t(d0,pZ);m0.prototype.l=function(a,b){var c=g.he(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
m0.prototype.B=function(a,b){var c=g.he(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.Gd("iv-card-sign-in-button",c).click();else{var d=parseInt(ina(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;o0(a,c);g.Iq(this.g.videoData.Dd,{Ac:{action_poll_vote:1},qb:{poll_id:a.id,index:d,session_token:a.F}});i0(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.at())&&g.Os(c,a.A)}};
m0.prototype.A=function(a){var b=g.x("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.B)});
w0(this,a,!0,c)};
m0.prototype.D=function(a){var b=g.x("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Qa(b,a.P,a.F,a.B));w0(this,a,!1,b)};g.t(D0,g.G);g.h=D0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.rD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&YY(a).subscribe("onEnter",d,this);e&&YY(a).subscribe("onExit",e,this);g.EJ(this.context.Z,[a])};
g.h.In=function(){this.context.i.subscribe("resize",this.ql,this)};
g.h.ia=function(){return this.Ca};
g.h.yi=function(a,b,c,d,e,f,k){this.context.g.da(a,"click",g.Qa(this.qm,b,c,d,e,f||[],k||0),this);this.context.g.da(a,"touchstart",g.Qa(function(){this.Qs=!1}),this);
this.context.g.da(a,"touchmove",g.Qa(function(){this.Qs=!0}),this)};
g.h.qm=function(a,b,c,d,e,f,k){if(this.Qs)return!1;k&&(k.stopPropagation(),k.preventDefault());toa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.C)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.ia())};
g.h.ql=function(){};g.t(G0,D0);g.h=G0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Oh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.ql=function(){var a=this.isAvailable();g.Ph(this.ia(),a);g.L(this.context.Z.getRootNode(),"ytp-iv-drawer-enabled",a);ZY(this.i)};
g.h.destroy=function(){this.i.wi(!1);this.i.getRootNode().removeChild(this.B);g.Xp(this.J);g.Er(this.ba);this.Y&&this.Y.dispose();this.D&&this.D.dispose();D0.prototype.destroy.call(this)};
g.h.ME=function(a){this.M.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.Mz=function(a){if(!g.bo(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.at(),c=this.g?this.g.Gb.u:this.H;b&&c&&oZ(b,[c]);this.g=a;J0(this)}bZ(this.ia())&&(2==this.context.Z.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Z.getAdState():void 0):(b=isNaN(void 0)?this.context.Z.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Z.getCurrentTime()),b&&a.Gb.teaserDurationMs&&this.i.wi(!0,{teaserText:a.Gb.teaserText,durationMs:a.Gb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.M.isActive()&&this.V)&&K0(this,a),this.ka.start(910+a.Gb.teaserDurationMs))}};
g.h.OL=function(a){this.u||(this.g=a,J0(this),K0(this,a),E0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.fC=function(){if(this.u){k0(this.context.logger,this.R,4,L0(this).i.close);var a=g.at();a&&this.P&&g.Os(a,this.P);F0(this)}};
g.h.pC=function(){g.L(this.B,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.UD=function(){var a=g.at(),b=L0(this);b=b?b.u:this.H;a&&b&&nZ(a,[b])};
g.h.TD=function(){var a=g.at(),b=L0(this);b=b?b.u:this.H;a&&b&&oZ(a,[b])};
g.h.XD=function(){var a=L0(this);l0(this.context.logger,8,a.l,a.i.aM);var b=g.at();b&&a&&nZ(b,[a.D,a.u])};
g.h.WD=function(){var a=g.at(),b=L0(this);a&&b&&oZ(a,[b.D])};
g.h.VD=function(a){var b=L0(this),c=g.at();this.g?a?(a=this.context.logger,l0(a,9,b.l,b.i.zs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Os(c,b.D)):(a=this.context.logger,l0(a,12,b.l,b.i.zs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Os(c,b.u)):(a=this.context.logger,k0(a,this.R,12,b.i.zs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Os(c,this.H))};
var H0={collaborator:W_,donation:Y_,episode:d0,movie:d0,playlist:Z_,poll:$_,productListing:a0,simple:X_,tip:b0,video:c0};g.t(M0,D0);M0.prototype.In=function(){D0.prototype.In.call(this);Boa(this)};
M0.prototype.show=function(){D0.prototype.show.call(this);var a=g.at(),b=this.annotation.data;a&&b&&(b=b.session_data)&&nZ(a,[g.Ks(b.itct)])};
M0.prototype.hide=function(){D0.prototype.hide.call(this);var a=g.at(),b=this.annotation.data;a&&b&&(b=b.session_data)&&oZ(a,[g.Ks(b.itct)])};g.t(N0,M0);g.h=N0.prototype;g.h.VL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Oh(a);this.g||(g.Mh(a,e.width),g.Mh(b,e.width));g.vh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.vh(c,"right","1px");this.o=!0;g.Ph(a,!0);this.A=new g.M(function(){g.J(this.ia(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.zD=function(a,b){g.eo(this.ia(),"iv-branding-active");this.B=new g.M((0,g.z)(function(){g.Ph(a,!1);this.g||g.Mh(b,0)},this),250);
this.B.start();this.o=!1};
g.h.show=function(){if(!this.isActive){M0.prototype.show.call(this);if(!this.D){g.J(this.ia(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Rd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Ph(this.i,!1);var b=g.Rd("DIV","branding-img-container",this.i);this.ia().appendChild(b);var c=g.Rd("DIV","iv-branding-context-name");g.ce(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.mV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Z),this.g.g(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Ph(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.vh(d,"right",this.u+"px");this.ia().appendChild(d);var e=this.annotation.Hb();e&&this.yi(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.M(g.Qa(this.zD,c,d),500,this);g.H(this,this.l);this.context.g.da(this.ia(),"mouseover",(0,g.z)(this.VL,this,c,d,b,a.image_height));this.context.g.da(this.ia(),"mouseout",(0,g.z)(this.l.start,this.l,void 0));this.D=!0}h0(this.context.logger,this.annotation.g);g.Ph(this.ia(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=$Y(a).width;c=g.Da(void 0)?void 0:b;g.Dh(a,c);f=new lZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,kna);g.H(this,f);this.context.l.da(f,
"begin",g.Qa(g.Ph,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(M0.prototype.hide.call(this),g.Ph(this.ia(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);M0.prototype.destroy.call(this)};g.t(O0,M0);g.h=O0.prototype;g.h.show=function(){this.isActive||(M0.prototype.show.call(this),this.H||(Coa(this),this.H=!0),g.Ph(this.ia(),!0),this.annotation&&this.annotation.g&&h0(this.context.logger,this.annotation.g),g.Dg(function(){g.eo(this.ia(),"iv-promo-inactive")},100,this),this.ia().removeAttribute("aria-hidden"),this.isActive=!0,R0(this),Q0(this),S0(this,this.B))};
g.h.hide=function(){this.isActive&&(g.J(this.ia(),"iv-promo-inactive"),this.isActive=!1,this.ia().setAttribute("aria-hidden",!0))};
g.h.qm=function(a,b,c,d,e,f,k){return this.u?!1:M0.prototype.qm.call(this,a,b,c,d,e,f,k)};
g.h.Lp=function(a,b){b.stopPropagation();Q0(this);S0(this,a);this.g.focus()};
g.h.eD=function(a){this.F=!0;this.Lp(500,a)};
g.h.dD=function(){this.F=!1;P0(this)};
g.h.VC=function(a){a.stopPropagation();this.hide();j0(this.context.logger,this.annotation.g)};
g.h.WC=function(a){a.stopPropagation();R0(this);this.u=!0;g.J(this.ia(),"iv-promo-collapsed-no-delay");this.A.start();j0(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();M0.prototype.destroy.call(this)};g.t(T0,g.ZJ);g.h=T0.prototype;g.h.Vb=function(a,b){if(!U0(g.V(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.go(b);c&&Z0(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(I0(this.g,b),ZY(this.player)),!0}return null};
g.h.getOptions=function(){return U0(g.V(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Gr=function(){if(this.o){var a=g.vJ(this.player).getVideoContentRect(!0);g.Nh(this.o.element,a.width,a.height);g.Dh(this.o.element,a.left,a.top)}if(this.g){var b=g.CJ(this.player);a=this.g;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.h.EJ=function(a){this.ec(a.state);g.U(a.state,2)&&(this.ud()&&this.ue()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.wi(!1))};
g.h.load=function(){g.ZJ.prototype.load.call(this);this.ec(g.uJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.z)(this.mI,this,b,this.H),d=(0,g.z)(function(){this.B=null},this);
g.us()&&(c=$0(this,c));c={format:"XML",Xc:c,onError:d,Ac:{}};a.isPharma&&(c.Ac.pharma="1");c.method="POST";c.withCredentials=!0;d=g.V(this.player);"gaming"==d.playerStyle&&(c.Ac.gaming="1");(b=d.J.get(b))&&a1(c,b);b=b&&(b.wl||b.vl);if(!a.jl||b)a.Dd?V0(this,a.Dd,c):(this.l=(0,g.z)(this.vE,this,c),this.player.addEventListener("videodatachange",this.l));g.LJ(this.player,this.o.element,4);this.Gr()};
g.h.ec=function(a){a=!a.isCued()&&!g.U(a,1024);g.NB(this.u,a);g.NB(this.o,a)};
g.h.vE=function(a){var b=this.player.getVideoData();b.Dd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),V0(this,b.Dd,a))};
g.h.unload=function(){moa(this.D);g.HJ(this.player,"annotations_module");g.Kb(this.i,function(a){a.destroy()});
g.Kb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,ZY(this.player));this.J=!1;this.B&&(this.B.abort(),this.B=null);this.i={};this.P={};this.u.hide();g.ZJ.prototype.unload.call(this);g.MB(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.mI=function(a,b,c){this.B=null;if(!X0(this,b,a)&&(a=g.yq(c)&&c.responseXML?c.responseXML:null)){Z0(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.rD(c,e,f);a.push(b)}}g.EJ(this.player,a)}};
g.h.Py=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Hoa(this):this.load())};
g.h.sE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,b1(this,a),h0(this.D,b.g))};
g.h.tE=function(a){c1(this,a.getId())};
g.h.dw=function(a){a&&(a.hide(),e1(this,"shown",!1,a.annotation.id),this.Fl(a.annotation,"hidden"))};
g.h.Yz=function(a){a&&(a.show(),e1(this,"shown",!0,a.annotation.id),this.Fl(a.annotation,"shown"))};
g.h.UK=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;t_(d.annotation,function(f){e=e||f.value});
Koa(this,a,b,e)}};
g.h.tH=function(a){if(a&&a.id){var b=a.Hb();if(b){var c=b_(b);if(c){var d=(0,g.z)(this.Fl,this,a,"click");if("new"==C0(c,b.target)||d1(this,b))d(),d=null;i0(this.D,a.g,d)}}}};
g.h.Fl=function(a,b){Yna(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!d1(this,c.url))){e=B0(c.url);var f=qoa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=Y0(this).Z,g.wX(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&Y0(this).Z.Yb()&&Y0(this).Z.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.V(this.player),(d=b_(c.url))?(f=z0(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Qa(roa,e.pageId,e.fc),d=new g.Wm(d),e=e(d.i),d.i=e,d=d.toString())):d=null,
d&&(this.player.pauseVideo(),c=C0(d,c.url.target),e=a.itct,"ei"in g.lq(d)&&(d=g.dh(d,"ei")),g.RK(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.uI=function(){e1(this,"playerControlShow",!1)};
g.h.wK=function(){e1(this,"playerControlShow",!0)};
g.h.uE=function(a){e1(this,"rollOver",!0,a.id)};
g.h.pg=function(a){e1(this,"rollOver",!1,a.id)};
g.h.WH=function(a){a&&a.id&&(this.i[a.id].l=!0,c1(this,a.id),j0(this.D,a.g),this.Fl(a,"close"),e1(this,"closed",!0,a.id))};
g.h.ud=function(){return!!this.g&&this.g.isAvailable()};
g.h.ue=function(){this.ud();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ud();this.g&&(a?c?E0(this.g,c,b):E0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):F0(this.g))};
g.h.wi=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.V(this.player).J.unsubscribe("vast_info_card_add",this.Py,this);g.eo(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.vs(a[b]);this.M.length=0;g.ZJ.prototype.T.call(this)};g.uU.annotations_module=T0;g.uU.creatorendscreen=JZ;})(_yt_player);
