# Generated by Django 3.0.4 on 2020-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirujal', '0006_auto_20200616_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
