# Generated by Django 3.0.4 on 2020-06-16 05:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sirujal', '0007_post1_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Post1',
            new_name='Videos',
        ),
    ]
