# Generated by Django 3.0.4 on 2020-06-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirujal', '0008_auto_20200616_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
